version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  format:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run format:check

workflows:	
  format:	
    jobs:	
      - format