version: 2.1

orbs:
  node: 'circleci/node:x.y'

jobs:
  format-check:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run format:check

workflows:
  format:
    jobs:
      - format-check