// Typography
export {default as Heading20} from './components/Heading20'
export {default as Heading23} from './components/Heading23'
export {default as Heading25} from './components/Heading25'
export {default as Heading30} from './components/Heading30'
export {default as Heading35} from './components/Heading35'
export {default as Heading38} from './components/Heading38'
export {default as Heading40} from './components/Heading40'
export {default as Heading50} from './components/Heading50'
export {default as Heading65} from './components/Heading68'
export {default as Heading68} from './components/Heading68'
export {default as Heading80} from './components/Heading80'
export {default as Text} from './components/Text'