name: build

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format:check

      - name: Build
        run: npm run build
