name: build

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: npm run lint
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format
        run: npm run format:check
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
