name: Test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Format
        run: npm run format:check

      - name: Build with Rollup
        run: npm run build
